FROM hasura/graphql-engine:v2.37.0-ce.cli-migrations-v3.ubuntu
# ce - communiti edition, cli migrations for migrations management
COPY migrations/ /hasura-migrations/
COPY metadata/ /hasura-metadata/
